# Generated by Django 4.1.2 on 2023-06-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('idCancha', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.CharField(max_length=50)),
                ('vetado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('idModerador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('replica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('idPartida', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50)),
                ('equipoA', models.CharField(max_length=50)),
                ('equipoB', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('idPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=15)),
                ('rut', models.CharField(max_length=15)),
                ('nombreTeam', models.CharField(max_length=50)),
                ('nick', models.CharField(max_length=50)),
                ('correoElectrico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('idTeam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPlayer',
            fields=[
                ('idEstadoPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.cancha', verbose_name='cancha')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.estado', verbose_name='estado')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.player', verbose_name='player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.team', verbose_name='estado')),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='moderador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.moderador', verbose_name='moderador'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.partida', verbose_name='partida'),
        ),
    ]
