# Generated by Django 4.1.2 on 2023-06-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airsoftcqb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='correoElectrico',
            new_name='correo',
        ),
    ]
