# Generated by Django 4.1.2 on 2023-06-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airsoftcqb', '0003_player_estado_alter_player_nombreteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='activo',
            new_name='nombreEstado',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='vetado',
        ),
    ]
