# Generated by Django 4.1.2 on 2023-06-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airsoftcqb', '0004_rename_activo_estado_nombreestado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='estado',
            new_name='idEstado',
        ),
    ]
