# Generated by Django 4.1.2 on 2023-07-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsoftcqb', '0005_rename_estado_player_idestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('idAsignacion', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RolPlayer',
            fields=[
                ('idRolPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Equipo',
        ),
        migrations.RemoveField(
            model_name='estadoplayer',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='estadoplayer',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estadoplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='estadoplayer',
            name='team',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='idTeam',
            new_name='idEquipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre',
            new_name='nombreEquipo',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='dia',
            new_name='lugar',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='equipoA',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='equipoB',
        ),
        migrations.AddField(
            model_name='partida',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='idEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.equipo', verbose_name='equipo'),
        ),
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='EstadoPlayer',
        ),
        migrations.DeleteModel(
            name='Moderador',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='idPartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.partida', verbose_name='partida'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='idPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.player', verbose_name='player'),
        ),
        migrations.AddField(
            model_name='player',
            name='idRolPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airsoftcqb.rolplayer', verbose_name='rolPlayer'),
        ),
    ]
